### ISSUE TITLE
Support for "Sec-WebSocket-Protocol" header

### ISSUE THREAD

**Issue by skateman** [imanel/websocket-ruby#26]
I'd like to use this driver with my [socket-to-socket proxy](https://github.com/skateman/surro-gate) and [noVNC](https://github.com/novnc/noVNC). Currently I'm receiving an error about the missing `Sec-WebSocket-Protocol` header. According to [RFC 6455](https://tools.ietf.org/html/rfc6455#section-11.3.4) a server should respond with the same headers, so it should not be a big change. Are you OK with accepting a PR?

**Comment by imanel** [comment]
Sure, feel free to send PR. Unfortunately I might be tight on time to implement it by myself before end of this week.

I would assume that reason for this bug is that I'm only sending back headers [required by spec](https://github.com/imanel/websocket-ruby/blob/master/lib/websocket/handshake/handler/base.rb#L11).

**Comment by skateman** [comment]
Is it okay if I open 2 PRs, one for the server and one for the client implementations?

**Comment by imanel** [comment]
No problem with that. I will release new version after they will be merged.

**Comment by skateman** [comment]
Finally I implemented them together ... looking forward for the new version.

**Comment by imanel** [comment]
New version released. Thanks a lot for your help!
